version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 226219512882.dkr.ecr.eu-west-2.amazonaws.com/tet
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag tet:latest 226219512882.dkr.ecr.eu-west-2.amazonaws.com/tet:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 226219512882.dkr.ecr.eu-west-2.amazonaws.com/tet:latest
